# Generated by Django 5.2.15 on 2026-07-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_issue_priority_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ssue',
            new_name='issue',
        ),
    ]
